# Generated by Django 5.2.3 on 2025-06-11 06:47

import services.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Inquiry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "customer_name",
                    models.CharField(
                        help_text="The full name of the customer inquiring (letters and spaces only, max 20 chars).",
                        max_length=20,
                        validators=[services.validators.validate_name_string],
                    ),
                ),
                (
                    "phone_number",
                    models.CharField(
                        help_text="The customer's phone number for a callback (must be 10 digits starting with 6,7,8,9).",
                        max_length=20,
                        validators=[services.validators.validate_phone_number],
                    ),
                ),
                (
                    "is_contacted",
                    models.BooleanField(
                        default=False,
                        help_text="Internal flag: Has Jose Car Care followed up on this inquiry?",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="Timestamp when the inquiry was submitted.",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Inquiries",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Service",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="The unique name of the detailing service (e.g., 'Exterior Detail').",
                        max_length=200,
                        unique=True,
                    ),
                ),
                (
                    "short_description",
                    models.CharField(
                        blank=True,
                        help_text="A brief, catchy summary of the service (1-2 sentences), ideal for lists or cards.",
                        max_length=255,
                    ),
                ),
                (
                    "long_description",
                    models.TextField(
                        blank=True,
                        help_text="A comprehensive, detailed description of what the service includes and its benefits.",
                        null=True,
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Controls whether this service is currently offered and visible on the website.",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="Timestamp when the service was first added.",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Timestamp when the service details were last updated.",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Services",
                "ordering": ["name"],
            },
        ),
    ]
