# Generated by Django 5.2.3 on 2025-06-11 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("services", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="service",
            name="image",
            field=models.ImageField(
                blank=True,
                help_text="An image representing the service. Will be displayed on service cards.",
                null=True,
                upload_to="service_images/",
            ),
        ),
    ]
